export interface Cookie {
  name: string,
  description: string,
  sunset: boolean,
  imageUrl: string,
}

export const Cookies: {[index: string]: Cookie} = {
  "Alkane Dragée Cookies": {
    name: "Alkane Dragée Cookies",
    description: "Deliver these unbreakable (?) treats to Sloane in Siren's Watch on Titan.",
    sunset: true,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/bd7ea2ccfa919e4ce8702377e0398dbc.jpg",
  },
  "Ascendant Oatmeal Raisin Cookies": {
    name: "Ascendant Oatmeal Raisin Cookies",
    description: "Deliver these delicious and nostalgic treats to Eris Morn on the Moon.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/a715b29f574c308f314634bd5d8a679f.jpg",
  },
  "Bittersweet Biscotti": {
    name: "Bittersweet Biscotti",
    description: "Deliver this thoughtful treat to Crow in the Tangled Shore.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/510a4671d21565baa1c1b18f0f10f291.jpg",
  },
  "Blueberry Crumblers": {
    name: "Blueberry Crumblers",
    description: "Deliver this fresh recipe to Shaw in the Cosmodrome.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/8e8528e4fc533b77cc86f5c34e2ab6f3.jpg",
  },
  "Bright-Dusted Snowballs": {
    name: "Bright-Dusted Snowballs",
    description: "Deliver this indulgent confection to Tess in the Tower.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/7d27ad2bc1c7c02215e15f31c90c36d4.jpg",
  },
  "Burnt Edge Transits": {
    name: "Burnt Edge Transits",
    description: "Deliver these highly sought-after treats to Master Rahool in the Tower Courtyard.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/72caa9e2c719879cd7f95f575f722a5b.jpg",
  },
  "Candy Dead Ghosts": {
    name: "Candy Dead Ghosts",
    description: "Deliver these… things to the Spider in his safehouse on the Tangled Shore.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/a32bb837abbc51c04a13240c18f89b28.jpg",
  },
  "Chocolate Ship Cookies": {
    name: "Chocolate Ship Cookies",
    description: "Deliver these finely tuned treats to Amanda Holliday in the Tower Hangar.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/9cc8a0c00a4421866016766e3e96bab6.jpg",
  },
  "Classic Butter Cookies": {
    name: "Classic Butter Cookies",
    description: "Deliver this traditional treat to Eva in the Tower.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/3a2819131bdbb451a0ea2d36c3d8d4a4.jpg",
  },
  "Dark Chocolate Motes": {
    name: "Dark Chocolate Motes",
    description: "Deliver these tempting morsels to the Drifter in the Annex.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/8a712271f7de627e4cf38eb392e8f6f9.jpg",
  },
  "Eliksni Birdseed": {
    name: "Eliksni Birdseed",
    description: "Deliver this high-end falcon food to Hawthorne's falcon Louis in the Tower Bazaar.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/98f8ff6b26899071de1b2b6c1fc819b0.jpg",
  },
  "Etheric Coldsnaps": {
    name: "Etheric Coldsnaps",
    description: "Deliver this frozen delicacy to Variks on Europa.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/1944ff2bf6e26bec541914ecf2202640.jpg",
  },
  "Fractal Rolls": {
    name: "Fractal Rolls",
    description: "Deliver these mysterious and obscure treats to Brother Vance in the Lighthouse on Mercury.",
    sunset: true,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/133fbe142d6204e5cc3cabf78f9aa166.jpg",
  },
  "Fried Sha-Dough": {
    name: "Fried Sha-Dough",
    description: "Deliver this opulent treat to the Visage of Calus aboard the Leviathan, and grow fat from strength.",
    sunset: true,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/2a8bc721fc847d64afa1c12af9f524df.jpg",
  },
  "Gentleman's Shortbread": {
    name: "Gentleman's Shortbread",
    description: "Deliver this tasteful, tasty treat to Devrim Kay in Trostland in the European Dead Zone.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/26a3ef37eeef4a9b0293a7537af2dda1.jpg",
  },
  "Hackleberry Tart": {
    name: "Hackleberry Tart",
    description: "Deliver this glitchy snack to Benedict 99-40 in the Annex.",
    sunset: true,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/d7dc32bb22c0e0bcc48f11b724f0fae7.jpg",
  },
  "Hot Crossfire Buns": {
    name: "Hot Crossfire Buns",
    description: "Deliver this impeccably crafted treat to Ada-1 in the Annex.",
    sunset: true,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/ff9810abba7b40868b013eb944fa5756.jpg",
  },
  "Gjallardoodles": {
    name: "Gjallardoodles",
    description: "Deliver these explosively delicious treats to Commander Zavala in the Tower Courtyard.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/bb0069e9efc9698f366d63fdce0c6db7.jpg",
  },
  "Ill-Fortune Cookies": {
    name: "Ill-Fortune Cookies",
    description: "Deliver these cursed yet delicious treats to Petra Venj wherever she can be found in the Reef.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/5c1d4e4af15100f1e5b2154dd50927a9.jpg",
  },
  "Infinite Forest Cake": {
    name: "Infinite Forest Cake",
    description: "Deliver this conflicted confection to Failsafe in the Exodus Black on Nessus.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/a6f21c09d4741ec548ccde23afc3e943.jpg",
  },
  "Javelin Mooncake": {
    name: "Javelin Mooncake",
    description: "Deliver this reminder of home to Ana Bray in the BrayTech Futurescape on Mars.",
    sunset: true,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/b3b6b52214114a7fbcbbfb3f11339859.jpg",
  },
  "Lavender Ribbon Cookies": {
    name: "Lavender Ribbon Cookies",
    description: "Deliver these sweet and triumphant treats to Saint-14 in the Tower Hangar.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/1cece8791684e7142627c7f2fa2da0dd.jpg",
  },
  "Radiolarian Pudding": {
    name: "Radiolarian Pudding",
    description: "Deliver this unfortunate reminder of Asher's past to him in the Rupture on Io.",
    sunset: true,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/78686cf2d331de14357442db5aa4a2fa.jpg",
  },
  "Strange Cookies": {
    name: "Strange Cookies",
    description: "Deliver these treats, whose will is clearly not their own, to Xûr wherever the Nine have wished him to be.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/72cc666b334a39996f74b09a4850e773.jpg",
  },
  "Telemetry Tapioca": {
    name: "Telemetry Tapioca",
    description: "Deliver this dismantling delight to Banshee-44 in the Tower Courtyard.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/85bc7a8c18b58e6286fec57dc28ce077.jpg",
  },
  "Thousand-Layer Cookie": {
    name: "Thousand-Layer Cookie",
    description: "Deliver this enticing, crafty treat to Riven in the Dreaming City.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/a7bc9d420b9afdfb3397f825a1d76185.jpg",
  },
  "Traveler Donut Holes": {
    name: "Traveler Donut Holes",
    description: "Deliver these unknowable alabaster spheres to Ikora Rey in the Tower Bazaar.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/b063620b4693d4a9df8f5aa62311e7d4.jpg",
  },
  "Vanilla Blades": {
    name: "Vanilla Blades",
    description: "Deliver these deadly delights to Lord Shaxx in the Tower Courtyard.",
    sunset: false,
    imageUrl: "https://www.bungie.net/common/destiny2_content/icons/015e27d918af700828cdf30c2504e5ef.jpg",
  },
}